fix: change body classes
h-enk/hyas pull request #165
Opened 2021-08-02 12:43 UTC by sean-pwd

This PR does include some breaking changes which you may want to consider if you are interested in the way that I generate classes for the body, from HUGO.

I have moved to slice arrays so spaces are not necessary.

As .Kind and .Type can both return "page" I have assigned the value of "default" to the .Type of "page", as this matches single.html and list.html in the layout/_default directory

My goal is to target classes based on the file structure of a hugo document, and stay as close to what is returned from the .Kind and .Type variables.

Some example outputs

.Kind        $template    .Type (page = default)
home                         default
page                single default
page                single contact
404                  single default
section              list     default
section              list     products
taxonomy         list     categories ??
taxonomyTerm list     category ??

I don't have experience with taxonomy/taxonomyTerm use cases so I put question marks there.

Any ideas? I have messed with Hugo's structure by changing .Type of "page" to "default" so I am looking for some feedback whether you would like to include this or not.

2021-08-24 15:11 UTC, h-enk commented
@sean-pwd, thanks for your input + sorry for my very late reply!

> I have moved to slice arrays so spaces are not necessary.

That's smart

Here are my thoughts on better body classes.

## Goal

Identify a page specifically or by type

## Cases

| Page type | Current example | Example #165  | Wish structure | Wish example |
|-------|--------|---|---|---|
| homepage | `<body class="home">` | `<body class="home  default">` | `<body class="single home">` | `<body class="single home">` |
| 404 page | `<body class="error404">` | `<body class="404 single default">` | `<body class="single error404">` | `<body class="single error404">` |
| page (not homepage/404) | `<body class="page single">` | `<body class="page single default">` | `<body class="single <page name>">` | `<body class="single about">` |
| section single page | `<body class="blog single">` | `<body class="page single blog">` | `<body class="single section <section name>">` | `<body class="single section blog">` |
| section list page | `<body class="blog list">` | `<body class="section list blog">` | `<body class="list section <section name>">` | `<body class="list section blog">` |
| taxonomy page | `<body class="categories list">` | `<body class="taxonomy list categories">` | `<body class="list taxonomy <taxonomy name>">` | `<body class="list taxonomy categories">` |
| term page | `<body class="categories list">` | `<body class="term  categories">` | `<body class="list term <term name>">` | `<body class="list term jamstack">` |


## Remarks

- The homepage + 404 page are special pages (own layout w/ fallback to default)
- Default always is the (lowest) fallback (no need to add this as classname , I think)
- A page is either single or list
- There's an issue w/ setting `<body class="404">` (can't remember though what it was), that's why `<body class="error404">`


## Resources

- [Hugo's Lookup Order](https://gohugo.io/templates/lookup-order/)
- [Taxonomies](https://gohugo.io/content-management/taxonomies/)

2021-08-25 04:42 UTC, sean-pwd commented
Thanks, I'll have a good look at it this week

On Wed, 25 Aug 2021, 1:11 am Henk Verlinde, ***@***.***>
wrote:

> @sean-pwd <https://github.com/sean-pwd>, thanks for your input + sorry
> for my very late reply!
>
> I have moved to slice arrays so spaces are not necessary.
>
> That's smart
>
> Here are my thoughts on better body classes.
> Goal
>
> Identify a page specifically or by type
> Cases
> Page type Current example Example #165
> <https://github.com/h-enk/hyas/pull/165> Wish structure Wish example
> homepage <body class="home"> <body class="home default"> <body
> class="single home"> <body class="single home">
> 404 page <body class="error404"> <body class="404 single default"> <body
> class="single error404"> <body class="single error404">
> page (not homepage/404) <body class="page single"> <body class="page
> single default"> <body class="single <page name>"> <body class="single
> about">
> section single page <body class="blog single"> <body class="page single
> blog"> <body class="single section <section name>"> <body class="single
> section blog">
> section list page <body class="blog list"> <body class="section list
> blog"> <body class="list section <section name>"> <body class="list
> section blog">
> taxonomy page <body class="categories list"> <body class="taxonomy list
> categories"> <body class="list taxonomy <taxonomy name>"> <body
> class="list taxonomy categories">
> term page <body class="categories list"> <body class="term categories"> <body
> class="list term <term name>"> <body class="list term jamstack"> Remarks
>
>    - The homepage + 404 page are special pages (own layout w/ fallback to
>    default)
>    - Default always is the (lowest) fallback (no need to add this as
>    classname , I think)
>    - A page is either single or list
>    - There's an issue w/ setting <body class="404"> (can't remember
>    though what it was), that's why <body class="error404">
>
> Resources
>
>    - Hugo's Lookup Order <https://gohugo.io/templates/lookup-order/>
>    - Taxonomies <https://gohugo.io/content-management/taxonomies/>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/h-enk/hyas/pull/165#issuecomment-904729697>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARTWGA7G436J3DUL452366TT6OZCTANCNFSM5BMVFYLA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&utm_campaign=notification-email>
> .
>

2021-08-28 15:57 UTC, sean-pwd commented
I have just committed a work in progress. 

Things to note: 

Section single and list both only show the section name (as requested)

Taxonomy and term both only show the taxonomy name (not as requested but matches section single/list and I think hugo lookup order )

Does this match https://gohugo.io/templates/lookup-order/  ? I am not 100% sure as I never use taxonomies.

If you think its ready to go, I will place it in a partial

2021-09-09 15:14 UTC, timtorres commented
> There's an issue w/ setting `<body class="404">` (can't remember though what it was), that's why `<body class="error404">`

This is because classes in CSS [cannot start with a number](https://www.w3.org/TR/CSS21/syndata.html#characters)

2021-09-14 13:47 UTC, h-enk commented
> This is because classes in CSS [cannot start with a number](https://www.w3.org/TR/CSS21/syndata.html#characters)

Ah yes, thanks

2021-09-15 06:06 UTC, h-enk requested changes
Nice! `<body class="list term <taxonomy name>">` i.s.o. `<body class="list term <term name>">` is OK for me. I don't think (tested some) there's a conflict in the lookup order,

Thanks so far. With the partial, we're good to merge

2021-09-15 07:22 UTC, sean-pwd commented
Great I'll make a partial.

I actually have no idea about taxonomies so let me know if you have any
ideas

On Wed, 15 Sep 2021, 4:06 pm Henk Verlinde, ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Nice! <body class="list term <taxonomy name>"> i.s.o. <body class="list
> term <term name>"> is OK for me. I don't think (tested some) there's a
> conflict in the lookup order,
>
> Thanks so far. With the partial, we're good to merge
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/h-enk/hyas/pull/165#pullrequestreview-754695917>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARTWGA2TYGPGCIG6S6U4OULUCAZXPANCNFSM5BMVFYLA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-09-15 10:30 UTC, h-enk commented
> I actually have no idea about taxonomies so let me know if you have any ideas

You're current logic is OK / works for me (meets the goal)!

2021-09-16 13:21 UTC, sean-pwd commented
I have pushed the update

2021-09-17 06:10 UTC, h-enk approved these changes

2021-09-17 06:12 UTC, merged